var scene, renderer, controls, activeCamera, perspCamera, orthoCamera;
var rotorGroup, statorGroup, cfdGroup;
var isOrthographic = false, isCfd = true;
var currentRPM = 0, currentAngle = 50, timeScale = 1.0;
var bladeMeshes = [], pivotGroups = [], armsT = [], armsB = [], levers = [], pushRods = [];
var topHub, bottomHub, motorMesh, shaftMesh;
var govWeights = [], govArmsT = [], govArmsB = [], topCollar, slidingCollar;
var statorPillars = [], topStruts = [], botStruts = [], mountLegs = [];
var streamlines = [];
var TRAIL_LENGTH = 15;
var audioCtx, windGain, bladeGain, windFilter, bladeOsc;
var audioInitialized = false, isAudioPlaying = false;
var chartTelemetry, chartParams;
var timeHistory = [], rpmHistory = [], torqueHistory = [], windHistory = [], wattsHistory = [];
var chartUpdateCounter = 0;